// Run with NODE_PATH pointing at Playwright and a local built preview server.
// Optional JIZURA_APNG_FIXTURE / JIZURA_APNG_REFERENCE add an independent real-file oracle.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),crypto=require('node:crypto');
const {proMode,openSource,timelineAction}=require('./ui_helpers.cjs');
const url=process.env.JIZURA_TEST_URL||'http://127.0.0.1:8765/',out=process.env.JIZURA_TEST_OUTPUT||path.join(process.cwd(),'apng-test-output');fs.mkdirSync(out,{recursive:true});
const signature=Buffer.from([137,80,78,71,13,10,26,10]);
function crc(b){let c=0xffffffff;for(const n of b){c^=n;for(let i=0;i<8;i++)c=c&1?0xedb88320^(c>>>1):c>>>1;}return(c^0xffffffff)>>>0;}
function chunk(name,data){const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(name,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;}
const u32=(...v)=>{const b=Buffer.alloc(v.length*4);v.forEach((n,i)=>b.writeUInt32BE(n,i*4));return b;};
const rgba=(...pixels)=>pixels.flat();
const red=[255,0,0,255],clear=[0,0,0,0],green=[0,255,0,255],yellow=[255,255,0,255];
const specs=[{w:2,p:rgba(red,red),num:1,den:10,dispose:0,blend:0},{w:1,p:[0,0,255,128],num:2,den:10,dispose:2,blend:1},{w:1,x:1,p:green,num:3,den:10,dispose:1,blend:0},{w:1,p:clear,num:4,den:10,dispose:0,blend:0},{w:1,p:yellow,num:5,den:10,dispose:0,blend:0}];
function imageData(frame){return zlib.deflateSync(Buffer.from([0,...frame.p]));}
function png(animation=true,excluded=false,plays=2,frames=specs){const ihdr=Buffer.concat([u32(2,1),Buffer.from([8,6,0,0,0])]),parts=[signature,chunk('IHDR',ihdr)];let seq=0;
 if(animation)parts.push(chunk('acTL',u32(frames.length,plays)));
 if(excluded||!animation)parts.push(chunk('IDAT',imageData({p:rgba(green,green)})));
 if(animation)frames.forEach((f,i)=>{const control=Buffer.alloc(26);[seq++,f.w,1,f.x||0,0].forEach((n,k)=>control.writeUInt32BE(n,k*4));control.writeUInt16BE(f.num,20);control.writeUInt16BE(f.den,22);control[24]=f.dispose;control[25]=f.blend;parts.push(chunk('fcTL',control));parts.push(!excluded&&i===0?chunk('IDAT',imageData(f)):chunk('fdAT',Buffer.concat([u32(seq++),imageData(f)])));});
 parts.push(chunk('IEND',Buffer.alloc(0)));return Buffer.concat(parts);}
const oracle=[rgba(red,red),rgba([127,0,128,255],red),rgba(red,green),rgba(clear,clear),rgba(yellow,clear)];
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.JIZURA_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{
 for(const lang of ['','en/']){
  const context=await browser.newContext({viewport:{width:1500,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));await page.goto(url+lang);await proMode(page);
  for(const excluded of [false,true])for(const fallback of [false,true]){
   const result=await page.evaluate(async({bytes,fallback})=>{const bitmap=window.createImageBitmap;if(fallback)window.createImageBitmap=undefined;try{
    const a=await J.decodeAPNG(new File([new Uint8Array(bytes)],'synthetic.png',{type:'image/png'})),asset={animation:a,element:a.element};const c=document.createElement('canvas');c.width=2;c.height=1;const x=c.getContext('2d'),frames=[];
    for(let i=0;i<a.frames.length;i++){x.clearRect(0,0,2,1);x.drawImage(await J.apngFrame(asset,i),0,0);frames.push([...x.getImageData(0,0,2,1).data]);}
    const cut={start:2,animationStart:0,animationLoop:'auto'},times=[2,2.099,2.1,2.3,2.6,3,3.5,5,6],indices=times.map(t=>J.apngFrameIndex(a,cut,t));
    const loops=['once','loop'].map(animationLoop=>J.apngFrameIndex(a,{...cut,animationLoop},5.1));const offset=J.apngFrameIndex(a,{...cut,animationStart:.3},2);const duration=a.duration,plays=a.plays;J.releaseAPNG(a);return{frames,duration,plays,indices,loops,offset,released:a.cache.size===0&&a.element.width===1};
   }finally{window.createImageBitmap=bitmap;}},{bytes:[...png(true,excluded)],fallback});
   result.frames.forEach((pixels,i)=>pixels.forEach((n,j)=>assert(Math.abs(n-oracle[i][j])<=1,`composition ${lang} frame ${i} pixel ${j}: ${n}/${oracle[i][j]}`)));assert.equal(result.duration,1.5);assert.equal(result.plays,2);assert.deepEqual(result.indices,[0,0,1,2,3,4,0,4,4]);assert.deepEqual(result.loops,[4,1]);assert.equal(result.offset,2);assert(result.released);
  }
  const edge=await page.evaluate(async({ordinary,zero,infinite,previous,bad})=>{const decode=b=>J.decodeAPNG(new File([new Uint8Array(b)],'edge.png',{type:'image/png'}));const a=await decode(zero),b=await decode(infinite),c=await decode(previous);const first=document.createElement('canvas');first.width=2;first.height=1;first.getContext('2d').drawImage(await J.apngFrame({animation:c},1),0,0);let rejected=0;for(const bytes of bad)try{await decode(bytes);}catch{rejected++;}return{ordinary:await decode(ordinary),delay:a.duration,inf:J.apngFrameIndex(b,{start:0},99.1),previous:[...first.getContext('2d').getImageData(0,0,2,1).data],rejected};},{ordinary:[...png(false)],zero:[...png(true,false,1,[{...specs[0],num:0,den:0}])],infinite:[...png(true,true,0)],previous:[...png(true,false,1,[{...specs[0],dispose:2},{...specs[2],dispose:0}])],bad:[(()=>{const b=png();b[50]^=1;return [...b];})(),[...png().subarray(0,-1)]]});
  assert.equal(edge.ordinary,null);assert.equal(edge.delay,.01);assert.equal(edge.inf,1);assert.deepEqual(edge.previous,rgba(clear,green));assert.equal(edge.rejected,2);
  // Import through both source tabs, including .apng with an unrecognized MIME type.
  await page.evaluate(()=>{J.ui.project=J.defaultProject();J.ui.project.lyrics='';J.ui.project.durationOverride=4;J.uiApi.syncUI();J.uiApi.replan();});
  for(const layer of ['media','foreground']){await openSource(page,layer);if(layer==='media')await page.locator('#mediaPane').evaluate((el,bytes)=>{const transfer=new DataTransfer();transfer.items.add(new File([new Uint8Array(bytes)],'animated.apng',{type:'application/octet-stream'}));el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));},[...png(true,true,0)]);else await page.locator('#mediaFiles').setInputFiles({name:'animated.apng',mimeType:'application/octet-stream',buffer:png(true,true,0)});try{await page.waitForFunction(layer=>!J.ui.projectBusy&&J.ui.project[layer].items.length===1,layer);}catch(e){console.error(await page.evaluate(()=>({busy:J.ui.projectBusy,items:[J.ui.project.media.items,J.ui.project.foreground.items],assets:J.mediaAssets.size,toast:document.querySelector('#toast')?.textContent})),errors);throw e;}assert.equal(await page.locator('.media-animation-loop').count(),1);await page.locator('.media-animation-loop').selectOption('loop');}
  let state=await page.evaluate(()=>({bg:J.ui.plan.media.cuts[0],fg:J.ui.plan.foreground.cuts[0]}));assert.equal(state.bg.animationLoop,'loop');assert.equal(state.fg.animationLoop,'loop');assert.equal(state.fg.animation.frames,5);
  const modal=page.locator('#cutDetailsDialog');for(const [offset,mode] of [[.2,'once'],[0,'loop']]){await timelineAction(page,'[data-layer="foreground"][data-index="0"]','details');await modal.locator('[data-detail-field="animationLoop"]').selectOption(mode);await modal.locator('[data-detail-field="animationStart"]').fill(String(offset));await modal.getByRole('button',{name:lang?'Apply':'適用',exact:true}).click();assert.deepEqual(await page.evaluate(()=>[J.ui.plan.foreground.cuts[0].animationStart,J.ui.plan.foreground.cuts[0].animationLoop]),[offset,mode]);}
  await page.evaluate(()=>{J.uiApi.seek(.1);document.getElementById('btnPlay').click();});await page.waitForFunction(()=>J.ui.t>.75);await page.evaluate(()=>J.uiApi.pause());const pausedTime=await page.evaluate(()=>J.ui.t);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>J.ui.t),pausedTime);await page.evaluate(()=>J.uiApi.seek(.1));const seekPixels=await page.evaluate(async()=>{await J.prepareMediaFrame(J.ui.plan,.1);const cut=J.ui.plan.foreground.cuts[0],c=document.createElement('canvas');c.width=2;c.height=1;const x=c.getContext('2d');x.drawImage(J.mediaFrameSource(J.mediaAssets.get(cut.itemId),cut,.1),0,0);return [...x.getImageData(0,0,2,1).data];});assert.deepEqual(seekPixels,oracle[1]);
  const split=await page.evaluate(()=>{const p=J.ui.project;p.durationOverride=4;J.uiApi.replan();J.uiApi.seek(.4);J.uiApi.splitMediaCut('foreground');return J.ui.plan.foreground.cuts.map(c=>({start:c.start,offset:c.animationStart,loop:c.animationLoop}));});assert.equal(split.length,2);assert.equal(split[1].offset,.4);assert.equal(split[1].loop,'loop');
  const prepared=await page.evaluate(async()=>{J.ui.exporting={};try{const asset=J.mediaAssets.get(J.ui.plan.media.cuts[0].itemId),base=J.ui.plan.media.cuts[0],cuts=[{...base,index:0,start:0,end:2,animationStart:0},{...base,index:1,start:0,end:2,animationStart:.5}];const c=document.createElement('canvas');c.width=2;c.height=1;const x=c.getContext('2d'),pixels=(asset,cut,time)=>{x.clearRect(0,0,2,1);x.drawImage(J.mediaFrameSource(asset,cut,time),0,0);return [...x.getImageData(0,0,2,1).data];};
    await J.prepareMediaFrame({...J.ui.plan,cuts:[],media:{...J.ui.plan.media,cuts},foreground:{cuts:[]}},.1);const simultaneous=cuts.map(c=>pixels(asset,c,.1));
    const transition=[{...base,index:0,start:0,end:.6},{...base,index:1,start:.6,end:2,trans:'crossfade',transDur:.35}];await J.prepareMediaFrame({...J.ui.plan,cuts:[],media:{...J.ui.plan.media,cuts:transition},foreground:{cuts:[]}},.65);const prior=pixels(asset,transition[0],.599);
    const fg=J.ui.plan.foreground.cuts[0],fgAsset=J.mediaAssets.get(fg.itemId),copy={...base,itemId:'@copy:foreground-source',start:0,end:2};await J.prepareMediaFrame({...J.ui.plan,cuts:[],layerVisibility:{foreground:false},media:{cuts:[copy]},foreground:{cuts:[fg]}},.31);const copied=pixels(fgAsset,fg,.31);
    const lyricCuts=[{index:0,start:0,end:.6},{index:1,start:.6,end:2,trans:'wipe',transDur:.35}],mediaCuts=[{...base,index:0,start:0,end:2}];await J.prepareMediaFrame({...J.ui.plan,fx:{koma:0},cuts:lyricCuts,media:{cuts:mediaCuts},foreground:{cuts:[]}},.65);const lyricPrior=pixels(asset,mediaCuts[0],.599);
    return{simultaneous,prior,copied,lyricPrior};}finally{J.ui.exporting=null;}});assert.deepEqual(prepared.simultaneous,[oracle[1],oracle[3]]);assert.deepEqual(prepared.prior,oracle[2]);assert.deepEqual(prepared.copied,oracle[2]);assert.deepEqual(prepared.lyricPrior,oracle[2]);
  await page.evaluate(()=>J.uiApi.flushSave());await page.reload();await page.waitForFunction(()=>[...J.mediaAssets.values()].filter(a=>a.animation).length===2);assert.equal(await page.evaluate(()=>J.ui.plan.foreground.cuts[1].animationStart),.4);
  const pack=await page.evaluate(async()=>{const bytes=await J.packProject(J.ui.project,null);window.apngPacked=bytes;const data=await J.unpackProject(bytes);return{bytes:[...new Uint8Array(await bytes.arrayBuffer())],animations:data.project.foreground.items.map(i=>i.animation),files:data.files.filter(e=>e.kind==='media').map(e=>e.file.size)};});assert.equal(pack.animations[0].frames,5);assert.deepEqual(pack.files,[png(true,true,0).length,png(true,true,0).length]);
  const fresh=await browser.newPage();await fresh.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));await fresh.goto(url+lang);await fresh.locator('#fileProject').setInputFiles({name:'animation.jizuraichi',mimeType:'application/octet-stream',buffer:Buffer.from(pack.bytes)});await fresh.waitForFunction(()=>!J.ui.projectBusy&&J.mediaAssets.size===2);assert.equal(await fresh.evaluate(()=>J.ui.plan.foreground.cuts[1].animationStart),.4);await fresh.context().close();
  await openSource(page,'foreground');await page.locator('#mediaFiles').setInputFiles({name:'static.png',mimeType:'image/png',buffer:png(false)});await page.waitForFunction(()=>!J.ui.projectBusy&&J.ui.project.foreground.items.length===2);assert.equal(await page.evaluate(()=>J.ui.project.foreground.items[1].animation||null),null);assert.equal(await page.evaluate(()=>J.mediaAssets.get(J.ui.project.foreground.items[1].id).element.naturalWidth),2);
  // Corrupt animation does not add a broken asset or remove valid sources.
  const broken=png();broken[50]^=1;await page.locator('#mediaFiles').setInputFiles({name:'broken.png',mimeType:'image/png',buffer:broken});await page.waitForFunction(()=>!J.ui.projectBusy);assert.equal(await page.evaluate(()=>J.ui.project.foreground.items.length),2);
  assert.deepEqual(errors,[]);console.log('PASS '+(lang||'ja')+' APNG composition/source/fallback/timing/loop/offset/import/split/multiple active cuts/storage/portable project/static PNG/corruption');
  await context.close();
 }
 if(process.env.JIZURA_APNG_FIXTURE){
  const fixture=fs.readFileSync(process.env.JIZURA_APNG_FIXTURE),reference=process.env.JIZURA_APNG_REFERENCE?JSON.parse(fs.readFileSync(process.env.JIZURA_APNG_REFERENCE)):null;
  const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));await page.goto(url);await proMode(page);await page.evaluate(()=>{J.ui.project=J.defaultProject();J.ui.project.lyrics='';J.uiApi.syncUI();J.uiApi.replan();});await openSource(page,'foreground');await page.locator('#mediaFiles').setInputFiles({name:'戦闘開始_降りてくる.png',mimeType:'image/png',buffer:fixture});await page.waitForFunction(()=>!J.ui.projectBusy&&J.ui.project.foreground.items.length===1,{},{timeout:60000});
  const result=await page.evaluate(async()=>{const item=J.ui.project.foreground.items[0],asset=J.mediaAssets.get(item.id),a=asset.animation,c=document.createElement('canvas');c.width=a.element.width;c.height=a.element.height;const x=c.getContext('2d'),digest=async b=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(n=>n.toString(16).padStart(2,'0')).join(''),hashes=[];for(let i=0;i<a.frames.length;i++){x.clearRect(0,0,c.width,c.height);x.drawImage(await J.apngFrame(asset,i),0,0);const pixels=x.getImageData(0,0,c.width,c.height).data;for(let p=0;p<pixels.length;p+=4)for(let ch=0;ch<3;ch++)pixels[p+ch]=Math.round(pixels[p+ch]*pixels[p+3]/255);hashes.push(await digest(pixels));}const packed=await J.unpackProject(await J.packProject(J.ui.project,null));return{animation:item.animation,size:[c.width,c.height],hashes,ends:a.ends,cache:a.cache.size,limit:a.limit,rawHash:await digest(await packed.files.find(f=>f.kind==='media').file.arrayBuffer())};});
  fs.writeFileSync(path.join(out,'apng-real-report.json'),JSON.stringify(result,null,2));
  const sample=await page.evaluate(async()=>{const a=[...J.mediaAssets.values()][0].animation;return [...new Uint8Array(await a.frames[1].arrayBuffer())];});fs.writeFileSync(path.join(out,'decoded-frame-1.png'),Buffer.from(sample));
  assert.equal(result.rawHash,hash(fixture));assert.equal(result.animation.frames,60);assert(Math.abs(result.animation.duration-4.25)<1e-9);assert.equal(result.animation.plays,1);assert.deepEqual(result.size,[1280,720]);assert(result.cache<=result.limit);if(reference){assert.deepEqual(result.hashes,reference.frames.map(f=>f.hash));let end=0;reference.frames.forEach((f,i)=>{end+=f.duration;assert(Math.abs(end-result.ends[i])<1e-9);});}
  // Real PNG and MP4 export. The normal renderer and normal export APIs are used.
  const exports=await page.evaluate(async()=>{const p=J.ui.project;p.lyrics='';p.durationOverride=1.5;p.videoSizeMode='custom';p.videoSize={w:320,h:180};p.fps=24;p.includeAudio=false;J.uiApi.replan();J.ui.exporting={};try{const png=await J.exportPNGZip({project:p,plan:J.ui.plan,transparent:true,every:6}),mp4=await J.exportMP4({project:p,plan:J.ui.plan,quality:'high'});return{png:[...new Uint8Array(await png.arrayBuffer())],mp4:[...new Uint8Array(await mp4.blob.arrayBuffer())]};}finally{J.ui.exporting=null;}});
  fs.writeFileSync(path.join(out,'apng-transparent-frames.zip'),Buffer.from(exports.png));fs.writeFileSync(path.join(out,'apng-animation.mp4'),Buffer.from(exports.mp4));assert(exports.png.length>1000);assert(exports.mp4.length>1000);
  const video=await page.evaluate(async bytes=>{J.ui.exporting={};const blob=new Blob([new Uint8Array(bytes)],{type:'video/mp4'}),url=URL.createObjectURL(blob),video=document.createElement('video'),c=document.createElement('canvas'),expected=document.createElement('canvas');c.width=expected.width=320;c.height=expected.height=180;const x=c.getContext('2d'),ex=expected.getContext('2d'),renderer=new J.Renderer(),hashes=[],differences=[];try{video.src=url;await new Promise((resolve,reject)=>{video.onloadeddata=resolve;video.onerror=()=>reject(Error('MP4 decode failed'));});for(const time of [.25,.5,1,.25]){await new Promise(resolve=>{video.onseeked=resolve;video.currentTime=time+.001;});x.drawImage(video,0,0);await J.prepareMediaFrame(J.ui.plan,time);renderer.frame(ex,J.ui.plan,time,{scale:320/J.ui.plan.W});const actual=x.getImageData(0,0,320,180).data,want=ex.getImageData(0,0,320,180).data;let error=0;for(let i=0;i<actual.length;i++)if(i%4!==3)error+=Math.abs(actual[i]-want[i]);differences.push(error/(320*180*3));hashes.push([...new Uint8Array(await crypto.subtle.digest('SHA-256',actual))].map(n=>n.toString(16).padStart(2,'0')).join(''));}return{duration:video.duration,hashes,differences};}finally{video.removeAttribute('src');video.load();URL.revokeObjectURL(url);J.ui.exporting=null;}},exports.mp4);assert(Math.abs(video.duration-1.5)<.05);assert.equal(video.hashes[0],video.hashes[3]);assert.notEqual(video.hashes[0],video.hashes[2]);video.differences.forEach(n=>assert(n<5,'MP4 decoded frames match renderer: mean RGB error '+n));result.video=video;
  // A screenshot requested immediately after a seek must wait for the correct APNG frame.
  await page.evaluate(()=>{const asset=[...J.mediaAssets.values()][0],a=asset.animation;for(const image of a.cache.values())image.close?.();a.cache.clear();window.apngScreenshot=null;window.apngOriginalSave=J.saveFile;J.saveFile=async(name,blob)=>{window.apngScreenshot={name,bytes:[...new Uint8Array(await blob.arrayBuffer())]};return 'saved';};J.uiApi.seek(.75);document.getElementById('previewScreenshot').click();});await page.waitForFunction(()=>window.apngScreenshot);const captured=await page.evaluate(()=>{J.saveFile=window.apngOriginalSave;return window.apngScreenshot;});fs.writeFileSync(path.join(out,'apng-preview-screenshot.png'),Buffer.from(captured.bytes));assert.match(captured.name,/0-750/);
  await page.evaluate(()=>{J.uiApi.seek(.5);J.ui.project.durationOverride=6;J.uiApi.replan();});await page.waitForTimeout(300);await page.screenshot({path:path.join(out,'apng-frame-early.png')});await page.evaluate(()=>J.uiApi.seek(1.1));await page.waitForTimeout(300);await page.screenshot({path:path.join(out,'apng-frame-later.png')});
  await page.locator('.media-animation-loop').selectOption('loop');await page.evaluate(()=>J.uiApi.seek(4.5));await page.waitForTimeout(300);await page.screenshot({path:path.join(out,'apng-loop.png')});
  const portable=await page.evaluate(async()=>[...new Uint8Array(await (await J.packProject(J.ui.project,null)).arrayBuffer())]);fs.writeFileSync(path.join(out,'apng-test-project.jizuraichi'),Buffer.from(portable));
  const restored=await browser.newPage({viewport:{width:1500,height:1000}});await restored.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));await restored.goto(url+'en/');await proMode(restored);await restored.locator('#fileProject').setInputFiles({name:'apng.jizuraichi',mimeType:'application/octet-stream',buffer:Buffer.from(portable)});await restored.waitForFunction(()=>!J.ui.projectBusy&&[...J.mediaAssets.values()].some(a=>a.animation?.frames.length===60),{},{timeout:60000});assert.equal(await restored.evaluate(()=>J.ui.plan.foreground.cuts[0].animationLoop),'loop');await restored.evaluate(()=>J.uiApi.flushSave());await restored.reload();await restored.waitForFunction(()=>[...J.mediaAssets.values()].some(a=>a.animation?.frames.length===60),{},{timeout:60000});await proMode(restored);await openSource(restored,'foreground');await restored.evaluate(()=>J.uiApi.seek(1.1));await restored.waitForTimeout(300);await restored.screenshot({path:path.join(out,'apng-restored-en.png')});await restored.context().close();
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'apng-real-report.json'),JSON.stringify(result,null,2));console.log('PASS original attachment: SHA256, all 60 frames' + (reference ? ' versus Pillow' : '') + ', duration/plays/transparency, bounded cache, raw project retention, real MP4 and transparent PNG exports');await page.context().close();
 }
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
