const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const locale of ['', 'en/']){
const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:8765/'+locale;await page.route('**/*',r=>r.request().url()===url?r.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(__dirname,'..',locale,'index.html'))}):r.abort());await page.goto(url);await page.locator('#modePro').click();
const before=await page.evaluate(()=>JSON.stringify(J.ui.project));
await page.locator('[data-preview-group="layout"][data-preview-key="center"]').evaluate(el=>el.click());await page.waitForTimeout(350);assert.equal(await page.locator('#effectPreviewDialog').evaluate(el=>el.open),true);assert.equal(await page.locator('#effectPreviewName').textContent(),await page.evaluate(()=>J.LAYOUTS.center.name));assert.equal(await page.evaluate(()=>JSON.stringify(J.ui.project)),before);await page.keyboard.press('Escape');
await page.locator('[data-preview-layer="foreground"]').first().evaluate(el=>el.click());await page.waitForFunction(()=>J.mediaAssets.has('__jizura_effect_preview__'));await page.waitForTimeout(200);assert.equal(await page.locator('.effect-preview-error').isVisible(),false);
const result=await page.evaluate(()=>{const failures=[],warnings=[],ctx=document.createElement('canvas').getContext('2d');ctx.canvas.width=320;ctx.canvas.height=180;const old=console.warn;console.warn=(...args)=>warnings.push(args.map(String).join(' '));let count=0;
try{for(const group of ['layout','enter','hold','exit','decor','treat','bg','cam','fx','trans'])for(const key of Object.keys(J.registry(group))){if(['blank','interlude','title'].includes(key))continue;try{const plan=J.makeEffectPreviewPlan(group,key);const r=new J.Renderer();for(const t of [.25,.7,2.8,3.15])r.frame(ctx,plan,t,{scale:320/plan.W,noHud:true});count++;}catch(e){failures.push(group+':'+key+':'+e.message)}}
for(const layer of ['media','foreground'])for(const key of Object.keys(J.MEDIA_TECH)){try{const plan=J.makeEffectPreviewPlan('media',key,layer,'__jizura_effect_preview__');const def=J.MEDIA_TECH[key],cut=plan[layer].cuts[0];if(def.stage&&cut[def.stage==='enter'?'entrance':'departure']!==key)throw Error('wrong phase');const r=new J.Renderer();for(const t of [.2,1.5,2.85,3.1])r.frame(ctx,plan,t,{scale:320/plan.W,noHud:true});count++;}catch(e){failures.push(layer+':'+key+':'+e.message)}}}finally{console.warn=old}return {count,failures,warnings:[...new Set(warnings)]}});
console.log(locale||'ja',JSON.stringify(result));assert.deepEqual(result.failures,[]);assert.deepEqual(result.warnings,[]);await page.locator('.effect-preview-close').click();await page.waitForFunction(()=>!J.mediaAssets.has('__jizura_effect_preview__'));assert.equal(await page.evaluate(()=>JSON.stringify(J.ui.project)),before);assert.deepEqual(errors,[]);await page.close();}}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
