// Run with NODE_PATH pointing at Playwright and a local built preview server.
// JIZURA_GIF_FIXTURES is a JSON array of paths; each GIF uses a same-stem
// -reference.json containing independent Pillow RGBA hashes, delays and loop metadata.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),crypto=require('node:crypto');
const {proMode,openSource,timelineAction}=require('./ui_helpers.cjs');
const url=process.env.JIZURA_TEST_URL||'http://127.0.0.1:8765/',out=process.env.JIZURA_TEST_OUTPUT||path.join(process.cwd(),'apng-test-output');fs.mkdirSync(out,{recursive:true});
const signature=Buffer.from([137,80,78,71,13,10,26,10]);
function crc(b){let c=0xffffffff;for(const n of b){c^=n;for(let i=0;i<8;i++)c=c&1?0xedb88320^(c>>>1):c>>>1;}return(c^0xffffffff)>>>0;}
function chunk(name,data){const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(name,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;}
const u32=(...v)=>{const b=Buffer.alloc(v.length*4);v.forEach((n,i)=>b.writeUInt32BE(n,i*4));return b;};
const rgba=(...pixels)=>pixels.flat();
const red=[255,0,0,255],clear=[0,0,0,0],green=[0,255,0,255],yellow=[255,255,0,255];
const specs=[{w:2,p:rgba(red,red),num:1,den:10,dispose:0,blend:0},{w:1,p:[0,0,255,128],num:2,den:10,dispose:2,blend:1},{w:1,x:1,p:green,num:3,den:10,dispose:1,blend:0},{w:1,p:clear,num:4,den:10,dispose:0,blend:0},{w:1,p:yellow,num:5,den:10,dispose:0,blend:0}];
function imageData(frame){return zlib.deflateSync(Buffer.from([0,...frame.p]));}
function png(animation=true,excluded=false,plays=2,frames=specs){const ihdr=Buffer.concat([u32(2,1),Buffer.from([8,6,0,0,0])]),parts=[signature,chunk('IHDR',ihdr)];let seq=0;
 if(animation)parts.push(chunk('acTL',u32(frames.length,plays)));
 if(excluded||!animation)parts.push(chunk('IDAT',imageData({p:rgba(green,green)})));
 if(animation)frames.forEach((f,i)=>{const control=Buffer.alloc(26);[seq++,f.w,1,f.x||0,0].forEach((n,k)=>control.writeUInt32BE(n,k*4));control.writeUInt16BE(f.num,20);control.writeUInt16BE(f.den,22);control[24]=f.dispose;control[25]=f.blend;parts.push(chunk('fcTL',control));parts.push(!excluded&&i===0?chunk('IDAT',imageData(f)):chunk('fdAT',Buffer.concat([u32(seq++),imageData(f)])));});
 parts.push(chunk('IEND',Buffer.alloc(0)));return Buffer.concat(parts);}
const oracle=[rgba(red,red),rgba([127,0,128,255],red),rgba(red,green),rgba(red,clear),rgba(yellow,clear)];
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');

function gif(animated=true,ignored=false,plays=2,frames=specs){
 const parts=[Buffer.from('GIF89a'),Buffer.from([2,0,1,0,0x82,0,0]),Buffer.from([0,0,0,255,0,0,0,0,255,0,255,0,255,255,0,0,0,0,0,0,0,0,0,0])];
 if(animated&&plays!==1)parts.push(Buffer.from([0x21,0xff,11]),Buffer.from('NETSCAPE2.0'),Buffer.from([3,1,plays===0?0:(plays-1)&255,plays===0?0:(plays-1)>>8,0]));
 (animated?frames:[specs[0]]).forEach(f=>{const disp=f.dispose===2?3:f.dispose===1?2:1,indices=[];for(let i=0;i<f.p.length;i+=4){const c=f.p.slice(i,i+4);indices.push(c[3]===0?0:c[0]===255?(c[1]===255?4:1):c[1]===255?3:2);}
 const codes=[];indices.forEach(n=>codes.push(8,n));codes.push(9);let bits=0,count=0;const packed=[];for(const n of codes){bits|=n<<count;count+=4;while(count>=8){packed.push(bits&255);bits>>>=8;count-=8;}}if(count)packed.push(bits&255);
 parts.push(Buffer.from([0x21,0xf9,4,(disp<<2)|1,(f.num*100/(f.den||100))&255,0,0,0,0x2c,f.x||0,0,0,0,f.w,0,1,0,0,3,packed.length,...packed,0]));});parts.push(Buffer.from([0x3b]));return Buffer.concat(parts);
}
const gifOracle=[rgba(red,red),rgba([0,0,255,255],red),rgba(red,green),rgba(red,clear),rgba(yellow,clear)];

function interlacedGIF(){
 const palette=Buffer.from([0,0,0,255,0,0,0,0,255,0,255,0,255,255,0,0,0,0,0,0,0,0,0,0]);
 const parts=[Buffer.from('GIF89a'),Buffer.from([1,0,8,0,0,0,0])];
 for(const indices of [[1,1,3,3,2,4,2,4],[4,4,2,2,3,1,3,1]]){const codes=indices.flatMap(n=>[8,n]).concat(9),data=[];for(let i=0;i<codes.length;i+=2)data.push(codes[i]|(codes[i+1]||0)<<4);parts.push(Buffer.from([0x2c,0,0,0,0,1,0,8,0,0xc2]),palette,Buffer.from([3,data.length,...data,0]));}
 return Buffer.concat([...parts,Buffer.from([0x3b])]);
}

(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.JIZURA_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{
 for(const lang of ['','en/']){
 const context=await browser.newContext({viewport:{width:1500,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));await page.goto(url+lang);await proMode(page);
 for(const fallback of [false,true]){const result=await page.evaluate(async({bytes,fallback})=>{const bitmap=window.createImageBitmap;if(fallback)window.createImageBitmap=undefined;try{const a=await J.decodeGIF(new File([new Uint8Array(bytes)],'fixture.gif',{type:'image/gif'})),asset={animation:a};const c=document.createElement('canvas');c.width=2;c.height=1;const x=c.getContext('2d'),frames=[];for(let i=0;i<a.frames.length;i++){x.clearRect(0,0,2,1);x.drawImage(await J.apngFrame(asset,i),0,0);frames.push([...x.getImageData(0,0,2,1).data]);}const indices=[0,.099,.1,.3,.6,1,1.5,3,4].map(t=>J.apngFrameIndex(a,{start:0},t));const values={frames,indices,duration:a.duration,plays:a.plays};J.releaseAPNG(a);return values;}finally{window.createImageBitmap=bitmap;}},{bytes:[...gif()],fallback});assert.deepEqual(result.frames,gifOracle);assert.deepEqual(result.indices,[0,0,1,2,3,4,0,4,4]);assert.equal(result.duration,1.5);assert.equal(result.plays,2);}
 const edge=await page.evaluate(async({zero,once,inf,staticGif,bad})=>{const decode=b=>J.decodeGIF(new File([new Uint8Array(b)],'fixture.gif'));const z=await decode(zero),o=await decode(once),i=await decode(inf);let rejected=0;for(const b of bad)try{await decode(b);}catch{rejected++;}return{zero:z.ends[0],once:o.plays,inf:i.plays,static:await decode(staticGif),rejected};},{zero:[...gif(true,false,1,[{...specs[0],num:0},specs[1]])],once:[...gif(true,false,1)],inf:[...gif(true,false,0)],staticGif:[...gif(false)],bad:[[...gif().subarray(0,-1)],[...gif().subarray(0,12)]]});assert.deepEqual(edge,{zero:.01,once:1,inf:0,static:null,rejected:2});
 const opaque=gif(true,false,1,[{...specs[0],w:1,p:red},{...specs[2]},{...specs[3]}]);let controls=0;for(let i=0;i<opaque.length-3;i++)if(opaque[i]===0x21&&opaque[i+1]===0xf9&&controls++<2)opaque[i+3]&=254;
 for(const [bytes,w,h,wanted] of [[opaque,2,1,[rgba(red,[0,0,0,255]),rgba(red,green),rgba(red,[0,0,0,255])]], [interlacedGIF(),1,8,[[red,[0,0,255,255],green,yellow,red,[0,0,255,255],green,yellow].flat(),[yellow,green,[0,0,255,255],red,yellow,green,[0,0,255,255],red].flat()]]]){const frames=await page.evaluate(async({bytes,w,h})=>{const a=await J.decodeGIF(new File([new Uint8Array(bytes)],'fixture.gif')),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d'),frames=[];for(let i=0;i<a.frames.length;i++){x.clearRect(0,0,w,h);x.drawImage(await J.apngFrame({animation:a},i),0,0);frames.push([...x.getImageData(0,0,w,h).data]);}J.releaseAPNG(a);return frames;},{bytes:[...bytes],w,h});assert.deepEqual(frames,wanted);}
 const gif87=interlacedGIF();gif87.write('GIF87a');assert.equal(await page.evaluate(bytes=>J.parseGIF(new Uint8Array(bytes)).frames.length,[...gif87]),2);
  // Import through both source tabs, including .apng with an unrecognized MIME type.
  await page.evaluate(()=>{J.ui.project=J.defaultProject();J.ui.project.lyrics='';J.ui.project.durationOverride=4;J.uiApi.syncUI();J.uiApi.replan();});
  for(const layer of ['media','foreground']){await openSource(page,layer);if(layer==='media')await page.locator('#mediaPane').evaluate((el,bytes)=>{const transfer=new DataTransfer();transfer.items.add(new File([new Uint8Array(bytes)],'animated.gif',{type:'application/octet-stream'}));el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));},[...gif(true,true,0)]);else await page.locator('#mediaFiles').setInputFiles({name:'animated.gif',mimeType:'application/octet-stream',buffer:gif(true,true,0)});try{await page.waitForFunction(layer=>!J.ui.projectBusy&&J.ui.project[layer].items.length===1,layer);}catch(e){console.error(await page.evaluate(()=>({busy:J.ui.projectBusy,items:[J.ui.project.media.items,J.ui.project.foreground.items],assets:J.mediaAssets.size,toast:document.querySelector('#toast')?.textContent})),errors);throw e;}assert.equal(await page.locator('.media-animation-loop').count(),1);await page.locator('.media-animation-loop').selectOption('loop');}
  let state=await page.evaluate(()=>({bg:J.ui.plan.media.cuts[0],fg:J.ui.plan.foreground.cuts[0]}));assert.equal(state.bg.animationLoop,'loop');assert.equal(state.fg.animationLoop,'loop');assert.equal(state.fg.animation.frames,5);
  const modal=page.locator('#cutDetailsDialog');for(const [offset,mode] of [[.2,'once'],[0,'loop']]){await timelineAction(page,'[data-layer="foreground"][data-index="0"]','details');await modal.locator('[data-detail-field="animationLoop"]').selectOption(mode);await modal.locator('[data-detail-field="animationStart"]').fill(String(offset));await modal.getByRole('button',{name:lang?'Apply':'適用',exact:true}).click();assert.deepEqual(await page.evaluate(()=>[J.ui.plan.foreground.cuts[0].animationStart,J.ui.plan.foreground.cuts[0].animationLoop]),[offset,mode]);}
  await page.evaluate(()=>{J.uiApi.seek(.1);document.getElementById('btnPlay').click();});await page.waitForFunction(()=>J.ui.t>.75);await page.evaluate(()=>J.uiApi.pause());const pausedTime=await page.evaluate(()=>J.ui.t);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>J.ui.t),pausedTime);await page.evaluate(()=>J.uiApi.seek(.1));const seekPixels=await page.evaluate(async()=>{await J.prepareMediaFrame(J.ui.plan,.1);const cut=J.ui.plan.foreground.cuts[0],c=document.createElement('canvas');c.width=2;c.height=1;const x=c.getContext('2d');x.drawImage(J.mediaFrameSource(J.mediaAssets.get(cut.itemId),cut,.1),0,0);return [...x.getImageData(0,0,2,1).data];});assert.deepEqual(seekPixels,gifOracle[1]);
  const split=await page.evaluate(()=>{const p=J.ui.project;p.durationOverride=4;J.uiApi.replan();J.uiApi.seek(.4);J.uiApi.splitMediaCut('foreground');return J.ui.plan.foreground.cuts.map(c=>({start:c.start,offset:c.animationStart,loop:c.animationLoop}));});assert.equal(split.length,2);assert.equal(split[1].offset,.4);assert.equal(split[1].loop,'loop');
  const prepared=await page.evaluate(async()=>{J.ui.exporting={};try{const asset=J.mediaAssets.get(J.ui.plan.media.cuts[0].itemId),base=J.ui.plan.media.cuts[0],cuts=[{...base,index:0,start:0,end:2,animationStart:0},{...base,index:1,start:0,end:2,animationStart:.5}];const c=document.createElement('canvas');c.width=2;c.height=1;const x=c.getContext('2d'),pixels=(asset,cut,time)=>{x.clearRect(0,0,2,1);x.drawImage(J.mediaFrameSource(asset,cut,time),0,0);return [...x.getImageData(0,0,2,1).data];};
    await J.prepareMediaFrame({...J.ui.plan,cuts:[],media:{...J.ui.plan.media,cuts},foreground:{cuts:[]}},.1);const simultaneous=cuts.map(c=>pixels(asset,c,.1));
    const transition=[{...base,index:0,start:0,end:.6},{...base,index:1,start:.6,end:2,trans:'crossfade',transDur:.35}];await J.prepareMediaFrame({...J.ui.plan,cuts:[],media:{...J.ui.plan.media,cuts:transition},foreground:{cuts:[]}},.65);const prior=pixels(asset,transition[0],.599);
    const fg=J.ui.plan.foreground.cuts[0],fgAsset=J.mediaAssets.get(fg.itemId),copy={...base,itemId:'@copy:foreground-source',start:0,end:2};await J.prepareMediaFrame({...J.ui.plan,cuts:[],layerVisibility:{foreground:false},media:{cuts:[copy]},foreground:{cuts:[fg]}},.31);const copied=pixels(fgAsset,fg,.31);
    const lyricCuts=[{index:0,start:0,end:.6},{index:1,start:.6,end:2,trans:'wipe',transDur:.35}],mediaCuts=[{...base,index:0,start:0,end:2}];await J.prepareMediaFrame({...J.ui.plan,fx:{koma:0},cuts:lyricCuts,media:{cuts:mediaCuts},foreground:{cuts:[]}},.65);const lyricPrior=pixels(asset,mediaCuts[0],.599);
    return{simultaneous,prior,copied,lyricPrior};}finally{J.ui.exporting=null;}});assert.deepEqual(prepared.simultaneous,[gifOracle[1],gifOracle[3]]);assert.deepEqual(prepared.prior,gifOracle[2]);assert.deepEqual(prepared.copied,gifOracle[2]);assert.deepEqual(prepared.lyricPrior,gifOracle[2]);
  await page.evaluate(()=>J.uiApi.flushSave());await page.reload();await page.waitForFunction(()=>[...J.mediaAssets.values()].filter(a=>a.animation).length===2);assert.equal(await page.evaluate(()=>J.ui.plan.foreground.cuts[1].animationStart),.4);
  const pack=await page.evaluate(async()=>{const bytes=await J.packProject(J.ui.project,null);window.apngPacked=bytes;const data=await J.unpackProject(bytes);return{bytes:[...new Uint8Array(await bytes.arrayBuffer())],animations:data.project.foreground.items.map(i=>i.animation),files:data.files.filter(e=>e.kind==='media').map(e=>e.file.size)};});assert.equal(pack.animations[0].frames,5);assert.deepEqual(pack.files,[gif(true,true,0).length,gif(true,true,0).length]);
  const fresh=await browser.newPage();await fresh.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));await fresh.goto(url+lang);await fresh.locator('#fileProject').setInputFiles({name:'animation.jizuraichi',mimeType:'application/octet-stream',buffer:Buffer.from(pack.bytes)});await fresh.waitForFunction(()=>!J.ui.projectBusy&&J.mediaAssets.size===2);assert.equal(await fresh.evaluate(()=>J.ui.plan.foreground.cuts[1].animationStart),.4);await fresh.context().close();
  await openSource(page,'foreground');await page.locator('#mediaFiles').setInputFiles({name:'static.png',mimeType:'image/png',buffer:png(false)});await page.waitForFunction(()=>!J.ui.projectBusy&&J.ui.project.foreground.items.length===2);assert.equal(await page.evaluate(()=>J.ui.project.foreground.items[1].animation||null),null);assert.equal(await page.evaluate(()=>J.mediaAssets.get(J.ui.project.foreground.items[1].id).element.naturalWidth),2);
  // Corrupt animation does not add a broken asset or remove valid sources.
  const broken=gif().subarray(0,-1);await page.locator('#mediaFiles').setInputFiles({name:'broken.gif',mimeType:'image/png',buffer:broken});await page.waitForFunction(()=>!J.ui.projectBusy);assert.equal(await page.evaluate(()=>J.ui.project.foreground.items.length),2);
  assert.deepEqual(errors,[]);console.log('PASS '+(lang||'ja')+' GIF source/timing/loop/offset/import/split/multiple active cuts/storage/portable project/static PNG/corruption');
  await context.close();
 }

// Independent Pillow frame oracle, original-byte preservation and real exports.
 if(process.env.JIZURA_GIF_FIXTURES) await verifyFixtures(browser);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});

async function verifyFixtures(browser){
 for(const file of JSON.parse(process.env.JIZURA_GIF_FIXTURES)){
  const bytes=fs.readFileSync(file),ref=JSON.parse(fs.readFileSync(file.replace(/\.gif$/,'-reference.json'))),name=path.basename(file,'.gif');
  const context=await browser.newContext({viewport:{width:1500,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));await page.goto(url);await proMode(page);await page.evaluate(()=>{const p=J.defaultProject();p.lyrics='';p.durationOverride=3.5;p.fps=8;p.includeAudio=false;p.videoSizeMode='custom';p.videoSize={w:160,h:160};J.ui.project=p;J.uiApi.syncUI();J.uiApi.replan();});
  for(const layer of ['media','foreground']){await openSource(page,layer);await page.locator('#mediaFiles').setInputFiles({name:name+'.gif',mimeType:'image/gif',buffer:bytes});await page.waitForFunction(layer=>!J.ui.projectBusy&&J.ui.project[layer].items.length===1,layer,{timeout:60000});await page.locator('.media-technique').first().selectOption('none');await page.locator('[data-media-phase="entrance"]').first().selectOption('none');await page.locator('[data-media-phase="departure"]').first().selectOption('none');}
  const result=await page.evaluate(async()=>{const item=J.ui.project.foreground.items[0],asset=J.mediaAssets.get(item.id),a=asset.animation,c=document.createElement('canvas');c.width=a.element.width;c.height=a.element.height;const x=c.getContext('2d'),digest=async data=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',data))].map(n=>n.toString(16).padStart(2,'0')).join(''),hashes=[];for(let i=0;i<a.frames.length;i++){x.clearRect(0,0,c.width,c.height);x.drawImage(await J.apngFrame(asset,i),0,0);hashes.push(await digest(x.getImageData(0,0,c.width,c.height).data));}return{animation:item.animation,size:[c.width,c.height],hashes,ends:a.ends,rawHash:await digest(await asset.file.arrayBuffer()),cache:a.cache.size,limit:a.limit};});
  assert.equal(result.animation.format,'gif');assert.equal(result.animation.frames,ref.frames.length);assert.equal(result.animation.plays,ref.loop===undefined||ref.loop===null?1:ref.loop===0?0:ref.loop+1);assert.deepEqual(result.size,ref.size);assert.equal(result.rawHash,ref.rawHash);assert.deepEqual(result.hashes,ref.frames.map(f=>f.hash));let end=0;ref.frames.forEach((f,i)=>{end+=f.duration;assert(Math.abs(end-result.ends[i])<1e-9);});assert(result.cache<=result.limit);
  await page.evaluate(()=>J.uiApi.flushSave());await page.reload();await page.waitForFunction(n=>[...J.mediaAssets.values()].filter(a=>a.animation?.frames.length===n).length===2,ref.frames.length,{timeout:60000});
  const packed=await page.evaluate(async()=>{const bytes=await J.packProject(J.ui.project,null);return [...new Uint8Array(await bytes.arrayBuffer())];});const restored=await browser.newPage();await restored.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));await restored.goto(url+'en/');await restored.locator('#fileProject').setInputFiles({name:'gif.jizuraichi',mimeType:'application/octet-stream',buffer:Buffer.from(packed)});await restored.waitForFunction(n=>!J.ui.projectBusy&&[...J.mediaAssets.values()].filter(a=>a.animation?.frames.length===n).length===2,ref.frames.length,{timeout:60000});assert.equal(await restored.evaluate(()=>J.ui.project.foreground.items[0].animation.format),'gif');const restoredHashes=await restored.evaluate(async()=>Promise.all([...J.mediaAssets.values()].map(async a=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',await a.file.arrayBuffer()))].map(n=>n.toString(16).padStart(2,'0')).join(''))));assert.deepEqual(restoredHashes,[ref.rawHash,ref.rawHash]);await restored.context().close();
  const exports=await page.evaluate(async()=>{J.ui.exporting={};try{const png=await J.exportPNGZip({project:J.ui.project,plan:J.ui.plan,transparent:true,every:4}),mp4=await J.exportMP4({project:{...J.ui.project,exportBitrate:2000000},plan:J.ui.plan,quality:'custom'});return{png:[...new Uint8Array(await png.arrayBuffer())],mp4:[...new Uint8Array(await mp4.blob.arrayBuffer())]};}finally{J.ui.exporting=null;}});fs.writeFileSync(path.join(out,name+'-transparent-frames.zip'),Buffer.from(exports.png));fs.writeFileSync(path.join(out,name+'-animation.mp4'),Buffer.from(exports.mp4));
  const video=await page.evaluate(async bytes=>{J.ui.exporting={};const blob=new Blob([new Uint8Array(bytes)],{type:'video/mp4'}),url=URL.createObjectURL(blob),v=document.createElement('video'),c=document.createElement('canvas'),want=document.createElement('canvas');c.width=want.width=c.height=want.height=160;const x=c.getContext('2d'),w=want.getContext('2d'),renderer=new J.Renderer(),hashes=[],differences=[];try{v.src=url;await new Promise((resolve,reject)=>{v.onloadeddata=resolve;v.onerror=()=>reject(Error('MP4 decode failed'));});for(const time of [.25,.875,1.5,3.25,.25]){await new Promise(resolve=>{v.onseeked=resolve;v.currentTime=time+.001;});x.drawImage(v,0,0);await J.prepareMediaFrame(J.ui.plan,time);renderer.frame(w,J.ui.plan,time,{scale:160/J.ui.plan.W});const actual=x.getImageData(0,0,160,160).data,expected=w.getImageData(0,0,160,160).data;let error=0;for(let i=0;i<actual.length;i++)if(i%4!==3)error+=Math.abs(actual[i]-expected[i]);differences.push(error/(160*160*3));hashes.push([...new Uint8Array(await crypto.subtle.digest('SHA-256',actual))].map(n=>n.toString(16).padStart(2,'0')).join(''));}return{duration:v.duration,hashes,differences};}finally{v.removeAttribute('src');v.load();URL.revokeObjectURL(url);J.ui.exporting=null;}},exports.mp4);
  fs.writeFileSync(path.join(out,name+"-video-diagnostic.json"),JSON.stringify(video,null,2));assert(Math.abs(video.duration-3.5)<.05);assert.equal(video.hashes[0],video.hashes[4]);assert.notEqual(video.hashes[0],video.hashes[2]);video.differences.forEach(n=>assert(n<5,'MP4 frame mean RGB error '+n));result.video=video;assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,name+'-report.json'),JSON.stringify(result,null,2));console.log('PASS '+name+': all '+ref.frames.length+' frames versus Pillow; background/foreground; storage/portable reload; MP4 frame comparison; PNG sequence');await context.close();
 }
}
