// NODE_PATH: Playwright installation; JIZURA_TEST_URL: a built browser edition.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const url=process.env.JIZURA_TEST_URL||'http://127.0.0.1:8765/',out=process.env.JIZURA_TEST_OUTPUT||path.join(process.cwd(),'manual-test-output');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const locale of ['','en/'])for(const width of [1500,390,320,568]){
 const context=await browser.newContext({viewport:{width,height:width===568?320:width===320?568:1000}}),page=await context.newPage(),errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));page.on('pageerror',e=>errors.push(e.message));await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));await page.goto(url+locale);await page.waitForFunction(()=>window.J?.uiApi);const initialTerms=await page.locator('#termsDlg .terms-section').allTextContents();const sentinel=await page.evaluate(()=>{J.ui.project.title='manual-test-unsaved';return JSON.stringify(J.ui.project);});
 for(let i=0;i<3;i++){await page.locator('#helpMenu summary').click();await page.locator('#btnTerms').click();await page.locator('#termsDlg').waitFor({state:'visible'});assert.equal(await page.locator('#termsTitle').innerText(),locale?'About this site':'このサイトについて');assert.deepEqual(await page.locator('#termsDlg .terms-section').allTextContents(),initialTerms);if(i===0)await page.keyboard.press('Escape');else await page.locator('#termsDlg button[value="close"]').click();await page.locator('#termsDlg').waitFor({state:'hidden'});await page.waitForFunction(()=>document.activeElement===document.querySelector('#helpMenu summary'));}
 await page.locator('#helpMenu summary').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#helpMenu').getAttribute('open'),null);await page.locator('#helpMenu summary').click();await page.locator('.brand').click();assert.equal(await page.locator('#helpMenu').getAttribute('open'),null);
 for(let iteration=0;iteration<2;iteration++){
  await page.locator('#helpMenu summary').click();const popup=page.waitForEvent('popup');await page.locator('#manualLink').click();const reader=await popup;await reader.waitForLoadState('domcontentloaded');assert.match(reader.url(),new RegExp('manual/'+(locale?'\\?lang=en':'')));assert.equal(await reader.evaluate(()=>window.opener===null),true);assert.equal(await page.locator('#helpMenu').getAttribute('open'),null);assert.equal(await reader.locator('.manual-page').count(),19);assert.equal(await reader.locator('#manualToc ol a').count(),19);await reader.locator('#page-01 img').waitFor();await reader.waitForFunction(()=>document.querySelector('#page-01 img').complete&&document.querySelector('#page-01 img').naturalWidth>=1999);
  async function choose(n){if(width<850)await reader.locator('#tocToggle').click();await reader.locator('#manualToc a[href="#page-'+String(n).padStart(2,'0')+'"]').click();await reader.waitForFunction(n=>document.querySelector('#pageCounter').textContent===n+' / 19',n);assert.equal(await reader.locator('#tocToggle').getAttribute('aria-expanded'),'false');assert.equal(await reader.locator('#manualToc a[aria-current="page"]').getAttribute('href'),'#page-'+String(n).padStart(2,'0'));const top=await reader.locator('#page-'+String(n).padStart(2,'0')).evaluate(el=>el.getBoundingClientRect().top);const headerHeight=await reader.locator('.reader-header').evaluate(el=>el.offsetHeight);assert(Math.abs(top-(headerHeight+16))<4||(n===19&&top>=headerHeight&&await reader.locator('#page-19').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight)),'selected page visible below header');}
  await choose(7);await choose(8);await reader.goBack();await reader.waitForFunction(()=>document.getElementById('pageCounter').textContent==='7 / 19');await reader.goForward();await reader.waitForFunction(()=>document.getElementById('pageCounter').textContent==='8 / 19');await reader.locator('#previousPage').click();await reader.waitForFunction(()=>document.getElementById('pageCounter').textContent==='7 / 19');await reader.locator('#nextPage').click();await reader.waitForFunction(()=>document.getElementById('pageCounter').textContent==='8 / 19');await choose(19);assert(await reader.locator('#nextPage').isDisabled());await choose(1);assert(await reader.locator('#previousPage').isDisabled());
  if(width<850){await reader.locator('#tocToggle').click();await reader.keyboard.press('Escape');assert.equal(await reader.locator('#tocToggle').getAttribute('aria-expanded'),'false');await reader.locator('#tocToggle').click();await reader.locator('#tocBackdrop').click({position:{x:width-15,y:20}});assert.equal(await reader.locator('#tocToggle').getAttribute('aria-expanded'),'false');}
  assert(await reader.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await reader.locator('#pageZoom').selectOption('2');assert(await reader.locator('#page-01 img').evaluate(el=>el.clientWidth>innerWidth*.9));await reader.locator('#pageZoom').selectOption('1');
  const pdfURL=await reader.locator('.reader-actions a[target="_blank"]').getAttribute('href'),pdf=await context.request.get(new URL(pdfURL,reader.url()).href);assert.equal(pdf.status(),200);assert.equal((await pdf.body()).subarray(0,5).toString(),'%PDF-');const digest=crypto.createHash('sha256').update(await pdf.body()).digest('hex');if(process.env.JIZURA_MANUAL_SHA256)assert.equal(digest,process.env.JIZURA_MANUAL_SHA256);
  if(iteration===0){await choose(8);await reader.locator('#page-08 img').scrollIntoViewIfNeeded();await reader.waitForFunction(()=>document.querySelector('#page-08 img').complete&&document.querySelector('#page-08 img').naturalWidth>0);await reader.screenshot({path:path.join(out,'reader-'+(locale?'en':'ja')+'-'+width+'.png')});const closed=reader.waitForEvent('close');await reader.locator('#closeReader').click();await closed;}else{await reader.locator('#editorLink').click();await reader.waitForURL(url+locale+'index.html');await reader.close();}
  assert.equal(await page.evaluate(()=>JSON.stringify(J.ui.project)),sentinel);
 }
 assert.deepEqual(errors,[]);await page.locator('#helpMenu summary').click();await page.screenshot({path:path.join(out,'menu-'+(locale?'en':'ja')+'-'+width+'.png')});console.log('PASS '+(locale||'ja')+' '+width+': menu/about/close/repeat/new-tab/19 pages/TOC/history/navigation/zoom/PDF bytes/editor unchanged');await context.close();
 }
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
