const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{for(const locale of ['', 'en/']){
const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:8765/'+locale;await page.route('**/*',r=>r.request().url()===url?r.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(__dirname,'..',locale,'index.html'))}):r.abort());await page.goto(url);
await page.evaluate(()=>{const p=J.defaultProject();p.lyrics='[00:00]長い歌詞の文章をここに記入します\n[00:05]次の歌詞です';p.title='Keep';p.durationOverride=10;p.fx.density=0;p.lyricBlankCuts=[{id:'blank',start:8,end:9}];p.foreground.manualCuts=true;p.foreground.cutCount=2;p.foreground.cutOverrides={0:{itemId:null},1:{itemId:null}};J.ui.project=p;J.uiApi.replan();J.uiApi.flushSave()});await page.reload();
await page.locator('#modePro').click();await page.locator('#sourceForeground').click();await page.locator('#mediaFiles').setInputFiles({name:'keep.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40"><rect width="40" height="40" fill="red"/></svg>')});await page.locator('#fontFile').setInputFiles('C:/Windows/Fonts/arial.ttf');await page.waitForFunction(()=>J.ui.project.userFonts?.some(f=>f.file));await page.evaluate(()=>J.uiApi.flushSave());await page.reload();
const before=await page.evaluate(()=>({project:JSON.parse(JSON.stringify(J.ui.project)),cuts:J.ui.plan.cuts.map(c=>[c.line,c.part,c.text,c.start,c.end])}));
const bytes=await page.evaluate(async()=>{const p=J.defaultProject();p.foreground=JSON.parse(JSON.stringify(J.ui.project.foreground));p.userFonts=JSON.parse(JSON.stringify(J.ui.project.userFonts));p.lyrics='do not import';p.title='do not import';p.fx.density=1;p.fx.glitch=.13;p.aspect='1:1';p.colors={enabled:true,text:'#ff0000'};p.media.effects={...J.mediaEffectSettings(p,'media'),motion:1.5};return Array.from(new Uint8Array(await (await J.packProject(p,null)).arrayBuffer()))});
await page.locator('#fileSettings').setInputFiles({name:'full.jizuraichi',mimeType:'application/octet-stream',buffer:Buffer.from(bytes)});await page.waitForFunction(()=>!J.ui.projectBusy&&J.ui.project.fx.glitch===.13);
let after=await page.evaluate(()=>({project:JSON.parse(JSON.stringify(J.ui.project)),cuts:J.ui.plan.cuts.map(c=>[c.line,c.part,c.text,c.start,c.end])}));assert.deepEqual(after.cuts,before.cuts);for(const key of ['lyrics','title','durationOverride','timing','lyricBlankCuts','lyricCutOptions','timelineLinks'])assert.deepEqual(after.project[key],before.project[key]);for(const layer of ['media','foreground'])for(const key of ['items','cutCount','cutOverrides','timing'])assert.deepEqual(after.project[layer][key],before.project[layer][key]);assert.equal(after.project.fx.density,1);assert.equal(after.project.aspect,'1:1');
await page.locator('#btnUndo').click();assert.equal(await page.evaluate(()=>J.ui.project.fx.glitch),before.project.fx.glitch);await page.locator('#btnRedo').click();assert.equal(await page.evaluate(()=>J.ui.project.fx.glitch),.13);
await page.evaluate(()=>{J.saveFile=async(name,blob)=>{window.savedSettings={name,loaded:await J.unpackProject(blob)}}});await page.locator('#projectMenu summary').click();await page.locator('#btnSaveSettings').click();await page.locator('#filenameDlg button[value="save"]').click();await page.waitForFunction(()=>!!window.savedSettings);const saved=await page.evaluate(()=>window.savedSettings);assert.match(saved.name,/_settings\.jizuraichi$/);assert.equal(saved.loaded.project.lyrics,'');assert.deepEqual(saved.loaded.project.overrides,{});assert.deepEqual(saved.loaded.project.lyricBlankCuts,[]);assert.deepEqual(saved.loaded.project.foreground.items,[]);assert.equal(saved.loaded.project.foreground.cutCount,0);assert.equal(saved.loaded.project.audioAsset,undefined);assert.equal(saved.loaded.files.length,1);assert.equal(saved.loaded.files[0].kind,'font');assert.equal(saved.loaded.project.fx.glitch,.13);
const snapshot=await page.evaluate(()=>JSON.stringify(J.ui.project));await page.locator('#fileSettings').setInputFiles({name:'bad.jizuraichi',mimeType:'application/octet-stream',buffer:Buffer.from('bad')});await page.waitForFunction(()=>!J.ui.projectBusy);assert.equal(await page.evaluate(()=>JSON.stringify(J.ui.project)),snapshot);assert.deepEqual(errors,[]);console.log(locale||'ja','settings export/import, cut preservation, undo/redo, invalid file OK');await page.close();
}}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
